### ISSUE TITLE
can't build on Yosemite (10.10.5)

### ISSUE THREAD

**Issue by masukomi** [shockone/black-screen#278]
see attached log 
[npm-debug.log.zip](https://github.com/shockone/black-screen/files/206541/npm-debug.log.zip)

Terminal output here:
```
 npm run package                                                                 

> black-screen@0.0.1 package /Users/krhodes/workspace/reference/javascript/black-screen
> gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns' --asar=true

[09:55:58] Using gulpfile ~/workspace/reference/javascript/black-screen/gulpfile.js
[09:55:58] Starting 'typescript'...
[09:55:58] Starting 'sass'...
[09:55:58] Starting 'copy-html'...
[09:55:58] Finished 'copy-html' after 28 ms
[09:55:58] gulp-notify: [Black Screen Watcher] SCSS has been compiled.
[09:55:58] Finished 'sass' after 383 ms

> black-screen@0.0.1 tsc /Users/krhodes/workspace/reference/javascript/black-screen
> tsc


13 import {Subject} from "rxjs/Subject";
                         ~~~~~~~~~~~~~~

src/views/4_PromptComponent.tsx(13,23): error TS2307: Cannot find module 'rxjs/Subject'.


13 import {Subject} from "rxjs/Subject";
                         ~~~~~~~~~~~~~~

src/views/4_PromptComponent.tsx(13,23): error TS2307: Cannot find module 'rxjs/Subject'.


npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/Users/krhodes/workspace/reference/javascript/black-screen/node_modules/.bin/npm" "run" "tsc"
npm ERR! node v5.0.0
npm ERR! npm  v3.7.1
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 tsc: `tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the black-screen@0.0.1 tsc script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs black-screen
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/krhodes/workspace/reference/javascript/black-screen/npm-debug.log
[09:56:02] 'typescript' errored after 3.98 s
[09:56:02] Error: Command `npm run tsc` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "run" "package"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE
npm ERR! black-screen@0.0.1 package: `gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns' --asar=true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the black-screen@0.0.1 package script 'gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns' --asar=true'.
npm ERR! This is most likely a problem with the black-screen package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build && electron-packager . "$npm_package_productName" --overwrite --platform=darwin --arch=x64 --version=$npm_package_electronVersion --out='/Applications' --icon='./icon.icns' --asar=true
npm ERR! You can get their info via:
npm ERR!     npm owner ls black-screen
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/krhodes/workspace/reference/javascript/black-screen/npm-debug.log
```

**Comment by shockone** [comment]
It builds on CI, must be something on your side. Did you try to re-install the packages?
